/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_john_xstream_XStream */

#ifndef _Included_com_john_xstream_XStream
#define _Included_com_john_xstream_XStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_john_xstream_XStream
 * Method:    reg2Server
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_john_xstream_XStream_reg2Server
  (JNIEnv *, jobject, jint, jstring, jint, jstring, jstring);

/*
 * Class:     com_john_xstream_XStream
 * Method:    unreg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_john_xstream_XStream_unreg
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_john_xstream_XStream
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_john_xstream_XStream_native_1setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_john_xstream_XStream
 * Method:    pumpVideoFrame
 * Signature: (I[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_john_xstream_XStream_pumpFrame
  (JNIEnv *, jobject, jint, jbyteArray, jintArray);
/*
 * Class:     com_john_xstream_XStream
 * Method:    pumpVideoFrame
 * Signature: (I[B[I)I
 */
JNIEXPORT void JNICALL Java_com_john_xstream_XStream_setIntParam
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
