/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_john_xstream_XStream */

#ifndef _Included_com_john_xstream_XStream
#define _Included_com_john_xstream_XStream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_john_xstream_XStream_CMD_QUIT
#define com_john_xstream_XStream_CMD_QUIT 58448L
#undef com_john_xstream_XStream_CMD_KEEPALIVE
#define com_john_xstream_XStream_CMD_KEEPALIVE 14L
#undef com_john_xstream_XStream_CMD_SEND
#define com_john_xstream_XStream_CMD_SEND 58623L
/*
 * Class:     com_john_xstream_XStream
 * Method:    reg2Server
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_john_xstream_XStream_reg2Server
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_john_xstream_XStream
 * Method:    unreg
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_john_xstream_XStream_unreg
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_john_xstream_XStream
 * Method:    native_setup
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_john_xstream_XStream_native_1setup
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
